#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="EBIPES")]
public partial class DataLINQDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertBudaya1(Budaya1 instance);
  partial void UpdateBudaya1(Budaya1 instance);
  partial void DeleteBudaya1(Budaya1 instance);
  partial void InsertGaleri(Galeri instance);
  partial void UpdateGaleri(Galeri instance);
  partial void DeleteGaleri(Galeri instance);
  partial void InsertProvinsi1(Provinsi1 instance);
  partial void UpdateProvinsi1(Provinsi1 instance);
  partial void DeleteProvinsi1(Provinsi1 instance);
  partial void InsertAnggota(Anggota instance);
  partial void UpdateAnggota(Anggota instance);
  partial void DeleteAnggota(Anggota instance);
  #endregion
	
	public DataLINQDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["EBIPESConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataLINQDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataLINQDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataLINQDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataLINQDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<Budaya1> Budaya1s
	{
		get
		{
			return this.GetTable<Budaya1>();
		}
	}
	
	public System.Data.Linq.Table<Galeri> Galeris
	{
		get
		{
			return this.GetTable<Galeri>();
		}
	}
	
	public System.Data.Linq.Table<Provinsi1> Provinsi1s
	{
		get
		{
			return this.GetTable<Provinsi1>();
		}
	}
	
	public System.Data.Linq.Table<Anggota> Anggotas
	{
		get
		{
			return this.GetTable<Anggota>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Budaya1")]
public partial class Budaya1 : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID_Budaya;
	
	private string _Nama_Budaya;
	
	private string _Jenis_Budaya;
	
	private string _Gambar_Budaya;
	
	private string _Ket_Budaya;
	
	private string _Provinsi;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_BudayaChanging(int value);
    partial void OnID_BudayaChanged();
    partial void OnNama_BudayaChanging(string value);
    partial void OnNama_BudayaChanged();
    partial void OnJenis_BudayaChanging(string value);
    partial void OnJenis_BudayaChanged();
    partial void OnGambar_BudayaChanging(string value);
    partial void OnGambar_BudayaChanged();
    partial void OnKet_BudayaChanging(string value);
    partial void OnKet_BudayaChanged();
    partial void OnProvinsiChanging(string value);
    partial void OnProvinsiChanged();
    #endregion
	
	public Budaya1()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Budaya", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID_Budaya
	{
		get
		{
			return this._ID_Budaya;
		}
		set
		{
			if ((this._ID_Budaya != value))
			{
				this.OnID_BudayaChanging(value);
				this.SendPropertyChanging();
				this._ID_Budaya = value;
				this.SendPropertyChanged("ID_Budaya");
				this.OnID_BudayaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nama_Budaya", DbType="VarChar(50)")]
	public string Nama_Budaya
	{
		get
		{
			return this._Nama_Budaya;
		}
		set
		{
			if ((this._Nama_Budaya != value))
			{
				this.OnNama_BudayaChanging(value);
				this.SendPropertyChanging();
				this._Nama_Budaya = value;
				this.SendPropertyChanged("Nama_Budaya");
				this.OnNama_BudayaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Jenis_Budaya", DbType="VarChar(50)")]
	public string Jenis_Budaya
	{
		get
		{
			return this._Jenis_Budaya;
		}
		set
		{
			if ((this._Jenis_Budaya != value))
			{
				this.OnJenis_BudayaChanging(value);
				this.SendPropertyChanging();
				this._Jenis_Budaya = value;
				this.SendPropertyChanged("Jenis_Budaya");
				this.OnJenis_BudayaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gambar_Budaya", DbType="VarChar(50)")]
	public string Gambar_Budaya
	{
		get
		{
			return this._Gambar_Budaya;
		}
		set
		{
			if ((this._Gambar_Budaya != value))
			{
				this.OnGambar_BudayaChanging(value);
				this.SendPropertyChanging();
				this._Gambar_Budaya = value;
				this.SendPropertyChanged("Gambar_Budaya");
				this.OnGambar_BudayaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ket_Budaya", DbType="VarChar(MAX)")]
	public string Ket_Budaya
	{
		get
		{
			return this._Ket_Budaya;
		}
		set
		{
			if ((this._Ket_Budaya != value))
			{
				this.OnKet_BudayaChanging(value);
				this.SendPropertyChanging();
				this._Ket_Budaya = value;
				this.SendPropertyChanged("Ket_Budaya");
				this.OnKet_BudayaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Provinsi", DbType="VarChar(50)")]
	public string Provinsi
	{
		get
		{
			return this._Provinsi;
		}
		set
		{
			if ((this._Provinsi != value))
			{
				this.OnProvinsiChanging(value);
				this.SendPropertyChanging();
				this._Provinsi = value;
				this.SendPropertyChanged("Provinsi");
				this.OnProvinsiChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Galeri")]
public partial class Galeri : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID_Gambar;
	
	private System.Data.Linq.Binary _Gambar;
	
	private System.Data.Linq.Binary _Judul_Gambar;
	
	private System.Data.Linq.Binary _Ket_Gambar;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_GambarChanging(int value);
    partial void OnID_GambarChanged();
    partial void OnGambarChanging(System.Data.Linq.Binary value);
    partial void OnGambarChanged();
    partial void OnJudul_GambarChanging(System.Data.Linq.Binary value);
    partial void OnJudul_GambarChanged();
    partial void OnKet_GambarChanging(System.Data.Linq.Binary value);
    partial void OnKet_GambarChanged();
    #endregion
	
	public Galeri()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Gambar", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID_Gambar
	{
		get
		{
			return this._ID_Gambar;
		}
		set
		{
			if ((this._ID_Gambar != value))
			{
				this.OnID_GambarChanging(value);
				this.SendPropertyChanging();
				this._ID_Gambar = value;
				this.SendPropertyChanged("ID_Gambar");
				this.OnID_GambarChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gambar", DbType="VarBinary(50)", UpdateCheck=UpdateCheck.Never)]
	public System.Data.Linq.Binary Gambar
	{
		get
		{
			return this._Gambar;
		}
		set
		{
			if ((this._Gambar != value))
			{
				this.OnGambarChanging(value);
				this.SendPropertyChanging();
				this._Gambar = value;
				this.SendPropertyChanged("Gambar");
				this.OnGambarChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Judul_Gambar", DbType="VarBinary(50)", UpdateCheck=UpdateCheck.Never)]
	public System.Data.Linq.Binary Judul_Gambar
	{
		get
		{
			return this._Judul_Gambar;
		}
		set
		{
			if ((this._Judul_Gambar != value))
			{
				this.OnJudul_GambarChanging(value);
				this.SendPropertyChanging();
				this._Judul_Gambar = value;
				this.SendPropertyChanged("Judul_Gambar");
				this.OnJudul_GambarChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ket_Gambar", DbType="VarBinary(50)", UpdateCheck=UpdateCheck.Never)]
	public System.Data.Linq.Binary Ket_Gambar
	{
		get
		{
			return this._Ket_Gambar;
		}
		set
		{
			if ((this._Ket_Gambar != value))
			{
				this.OnKet_GambarChanging(value);
				this.SendPropertyChanging();
				this._Ket_Gambar = value;
				this.SendPropertyChanged("Ket_Gambar");
				this.OnKet_GambarChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Provinsi1")]
public partial class Provinsi1 : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID_Prov;
	
	private string _Nama_Prov;
	
	private string _Ibu_Kota_Prov;
	
	private string _Logo_Prov;
	
	private string _Luas_Prov;
	
	private string _Arti_Logo;
	
	private string _Ket_Prov;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_ProvChanging(int value);
    partial void OnID_ProvChanged();
    partial void OnNama_ProvChanging(string value);
    partial void OnNama_ProvChanged();
    partial void OnIbu_Kota_ProvChanging(string value);
    partial void OnIbu_Kota_ProvChanged();
    partial void OnLogo_ProvChanging(string value);
    partial void OnLogo_ProvChanged();
    partial void OnLuas_ProvChanging(string value);
    partial void OnLuas_ProvChanged();
    partial void OnArti_LogoChanging(string value);
    partial void OnArti_LogoChanged();
    partial void OnKet_ProvChanging(string value);
    partial void OnKet_ProvChanged();
    #endregion
	
	public Provinsi1()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Prov", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID_Prov
	{
		get
		{
			return this._ID_Prov;
		}
		set
		{
			if ((this._ID_Prov != value))
			{
				this.OnID_ProvChanging(value);
				this.SendPropertyChanging();
				this._ID_Prov = value;
				this.SendPropertyChanged("ID_Prov");
				this.OnID_ProvChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nama_Prov", DbType="VarChar(50)")]
	public string Nama_Prov
	{
		get
		{
			return this._Nama_Prov;
		}
		set
		{
			if ((this._Nama_Prov != value))
			{
				this.OnNama_ProvChanging(value);
				this.SendPropertyChanging();
				this._Nama_Prov = value;
				this.SendPropertyChanged("Nama_Prov");
				this.OnNama_ProvChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ibu_Kota_Prov", DbType="VarChar(50)")]
	public string Ibu_Kota_Prov
	{
		get
		{
			return this._Ibu_Kota_Prov;
		}
		set
		{
			if ((this._Ibu_Kota_Prov != value))
			{
				this.OnIbu_Kota_ProvChanging(value);
				this.SendPropertyChanging();
				this._Ibu_Kota_Prov = value;
				this.SendPropertyChanged("Ibu_Kota_Prov");
				this.OnIbu_Kota_ProvChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Logo_Prov", DbType="VarChar(50)")]
	public string Logo_Prov
	{
		get
		{
			return this._Logo_Prov;
		}
		set
		{
			if ((this._Logo_Prov != value))
			{
				this.OnLogo_ProvChanging(value);
				this.SendPropertyChanging();
				this._Logo_Prov = value;
				this.SendPropertyChanged("Logo_Prov");
				this.OnLogo_ProvChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Luas_Prov", DbType="VarChar(50)")]
	public string Luas_Prov
	{
		get
		{
			return this._Luas_Prov;
		}
		set
		{
			if ((this._Luas_Prov != value))
			{
				this.OnLuas_ProvChanging(value);
				this.SendPropertyChanging();
				this._Luas_Prov = value;
				this.SendPropertyChanged("Luas_Prov");
				this.OnLuas_ProvChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Arti_Logo", DbType="VarChar(MAX)")]
	public string Arti_Logo
	{
		get
		{
			return this._Arti_Logo;
		}
		set
		{
			if ((this._Arti_Logo != value))
			{
				this.OnArti_LogoChanging(value);
				this.SendPropertyChanging();
				this._Arti_Logo = value;
				this.SendPropertyChanged("Arti_Logo");
				this.OnArti_LogoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ket_Prov", DbType="VarChar(MAX)")]
	public string Ket_Prov
	{
		get
		{
			return this._Ket_Prov;
		}
		set
		{
			if ((this._Ket_Prov != value))
			{
				this.OnKet_ProvChanging(value);
				this.SendPropertyChanging();
				this._Ket_Prov = value;
				this.SendPropertyChanged("Ket_Prov");
				this.OnKet_ProvChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Anggota")]
public partial class Anggota : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _User_Name;
	
	private string _Nama_User;
	
	private string _Password;
	
	private string _Email;
	
	private string _Jenis_Kelamin;
	
	private string _Alamat;
	
	private string _Tempat_Lahir;
	
	private string _Tgl_Lahir;
	
	private string _Foto_Profil;
	
	private int _IDAnggota;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUser_NameChanging(string value);
    partial void OnUser_NameChanged();
    partial void OnNama_UserChanging(string value);
    partial void OnNama_UserChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnJenis_KelaminChanging(string value);
    partial void OnJenis_KelaminChanged();
    partial void OnAlamatChanging(string value);
    partial void OnAlamatChanged();
    partial void OnTempat_LahirChanging(string value);
    partial void OnTempat_LahirChanged();
    partial void OnTgl_LahirChanging(string value);
    partial void OnTgl_LahirChanged();
    partial void OnFoto_ProfilChanging(string value);
    partial void OnFoto_ProfilChanged();
    partial void OnIDAnggotaChanging(int value);
    partial void OnIDAnggotaChanged();
    #endregion
	
	public Anggota()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string User_Name
	{
		get
		{
			return this._User_Name;
		}
		set
		{
			if ((this._User_Name != value))
			{
				this.OnUser_NameChanging(value);
				this.SendPropertyChanging();
				this._User_Name = value;
				this.SendPropertyChanged("User_Name");
				this.OnUser_NameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nama_User", DbType="VarChar(50)")]
	public string Nama_User
	{
		get
		{
			return this._Nama_User;
		}
		set
		{
			if ((this._Nama_User != value))
			{
				this.OnNama_UserChanging(value);
				this.SendPropertyChanging();
				this._Nama_User = value;
				this.SendPropertyChanged("Nama_User");
				this.OnNama_UserChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(50)")]
	public string Password
	{
		get
		{
			return this._Password;
		}
		set
		{
			if ((this._Password != value))
			{
				this.OnPasswordChanging(value);
				this.SendPropertyChanging();
				this._Password = value;
				this.SendPropertyChanged("Password");
				this.OnPasswordChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
	public string Email
	{
		get
		{
			return this._Email;
		}
		set
		{
			if ((this._Email != value))
			{
				this.OnEmailChanging(value);
				this.SendPropertyChanging();
				this._Email = value;
				this.SendPropertyChanged("Email");
				this.OnEmailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Jenis_Kelamin", DbType="VarChar(50)")]
	public string Jenis_Kelamin
	{
		get
		{
			return this._Jenis_Kelamin;
		}
		set
		{
			if ((this._Jenis_Kelamin != value))
			{
				this.OnJenis_KelaminChanging(value);
				this.SendPropertyChanging();
				this._Jenis_Kelamin = value;
				this.SendPropertyChanged("Jenis_Kelamin");
				this.OnJenis_KelaminChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Alamat", DbType="VarChar(50)")]
	public string Alamat
	{
		get
		{
			return this._Alamat;
		}
		set
		{
			if ((this._Alamat != value))
			{
				this.OnAlamatChanging(value);
				this.SendPropertyChanging();
				this._Alamat = value;
				this.SendPropertyChanged("Alamat");
				this.OnAlamatChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tempat_Lahir", DbType="VarChar(50)")]
	public string Tempat_Lahir
	{
		get
		{
			return this._Tempat_Lahir;
		}
		set
		{
			if ((this._Tempat_Lahir != value))
			{
				this.OnTempat_LahirChanging(value);
				this.SendPropertyChanging();
				this._Tempat_Lahir = value;
				this.SendPropertyChanged("Tempat_Lahir");
				this.OnTempat_LahirChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tgl_Lahir", DbType="VarChar(50)")]
	public string Tgl_Lahir
	{
		get
		{
			return this._Tgl_Lahir;
		}
		set
		{
			if ((this._Tgl_Lahir != value))
			{
				this.OnTgl_LahirChanging(value);
				this.SendPropertyChanging();
				this._Tgl_Lahir = value;
				this.SendPropertyChanged("Tgl_Lahir");
				this.OnTgl_LahirChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Foto_Profil", DbType="VarChar(50)")]
	public string Foto_Profil
	{
		get
		{
			return this._Foto_Profil;
		}
		set
		{
			if ((this._Foto_Profil != value))
			{
				this.OnFoto_ProfilChanging(value);
				this.SendPropertyChanging();
				this._Foto_Profil = value;
				this.SendPropertyChanged("Foto_Profil");
				this.OnFoto_ProfilChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDAnggota", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int IDAnggota
	{
		get
		{
			return this._IDAnggota;
		}
		set
		{
			if ((this._IDAnggota != value))
			{
				this.OnIDAnggotaChanging(value);
				this.SendPropertyChanging();
				this._IDAnggota = value;
				this.SendPropertyChanged("IDAnggota");
				this.OnIDAnggotaChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
