//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class admin1
{
    public int adminid { get; set; }
    public string username { get; set; }
    public string password { get; set; }
}

public partial class anggota
{
    public int id_anggota { get; set; }
    public string nama_anggota { get; set; }
    public string password { get; set; }
    public string email { get; set; }
    public string jenis_kelamin { get; set; }
}

public partial class budaya1
{
    public int id_budaya { get; set; }
    public string nama_budaya { get; set; }
    public string provinsi { get; set; }
    public string jenis_budaya { get; set; }
    public string ket { get; set; }
    public string ket_img { get; set; }
    public string sumber { get; set; }
    public byte[] image { get; set; }
    public string file_path { get; set; }
    public Nullable<int> id_prov { get; set; }
    public Nullable<int> id_jenis { get; set; }

    public virtual Table_Jenis_Budaya Table_Jenis_Budaya { get; set; }
    public virtual provinsi provinsi1 { get; set; }
}

public partial class provinsi
{
    public provinsi()
    {
        this.budaya1 = new HashSet<budaya1>();
    }

    public int id_prov { get; set; }
    public string nama_prov { get; set; }
    public string ibukota_prov { get; set; }
    public byte[] logo_prov { get; set; }
    public string ket { get; set; }
    public string file_path { get; set; }

    public virtual ICollection<budaya1> budaya1 { get; set; }
}

public partial class sysdiagrams
{
    public string name { get; set; }
    public int principal_id { get; set; }
    public int diagram_id { get; set; }
    public Nullable<int> version { get; set; }
    public byte[] definition { get; set; }
}

public partial class Table_Jenis_Budaya
{
    public Table_Jenis_Budaya()
    {
        this.budaya1 = new HashSet<budaya1>();
    }

    public int id_jenis_budaya { get; set; }
    public string nama_jenis_budaya { get; set; }

    public virtual ICollection<budaya1> budaya1 { get; set; }
}
