//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class PES17Entities : DbContext
{
    public PES17Entities()
        : base("name=PES17Entities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public DbSet<admin1> admin1 { get; set; }
    public DbSet<anggota> anggota { get; set; }
    public DbSet<provinsi> provinsi { get; set; }
    public DbSet<sysdiagrams> sysdiagrams { get; set; }
    public DbSet<Table_Jenis_Budaya> Table_Jenis_Budaya { get; set; }
    public DbSet<budaya1> budaya1 { get; set; }
}
